# Generated by Django 4.1.7 on 2023-04-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(
                choices=[
                    ('Nebulosa', 'Nebulosa'),
                    ('Estrela', 'Estrela'),
                    ('GALAXIA', 'Galaxia'),
                    ('PLANETA', 'Planeta'),
                ],
                default='',
                max_length=100,
            ),
        ),
    ]
